name: branches

on:
  push:
    branches:
      - '*'
      - '!master'
      
  pull_request:
    branches:
      - '*'
      - '!master'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      env:
        NPM_CONFIG_PREFIX: ~/.npm-global
      run: |
        mkdir -p ~/.npm-global
        npm config set prefix '~/.npm-global'
        export PATH=~/.npm-global/bin:$PATH
        source ~/.profile
        npm install -g firebase-tools@8.5.0
        bash ./ci.sh
